### ISSUE TITLE
🐳 docker-compose issue

### ISSUE THREAD

**Issue by kauefraga** [kauefraga/zssn#1]
Postgres **password** is exposed in file (not secure)

- I think a .env file is the way, but how?

**Comment by msafronov** [comment]
hi! you can just create an _.env_ file:

```
POSTGRES_PASSWORD=1234
```

..and add [env_file ](https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file)option inside _docker-compose.yaml_ like this:

```yml
version: '3'

services:
  db:
    image: postgres
    # environment:
    #   POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - '.env'
```
